#!/usr/bin/env python3

import shutil
import sys 
import glob
import os
import argparse
                
parser = argparse.ArgumentParser()
parser.add_argument('src_path', action='store', type=str, help='"path to vst dll folder/*" (** for subdirectories); Path is enclosed in quotes, for example linvstconvert32 "/home/user/vst/*" or linvstconvert32 "/home/user/vst/**" for subdirectories')
args = parser.parse_args()
files = glob.glob(args.src_path, recursive=True)

for file in files:
    if file.endswith( ".dll" ) or file.endswith( ".DLL" ) or file.endswith( ".Dll" ):
          sofile = file[ 0: -4 ] + ".so"
          shutil.copyfile( '/usr/share/LinVst/32bit/linvst.so', sofile ) 

