#!/usr/bin/env python3

import argparse
import os
import shutil

parser = argparse.ArgumentParser(description='Convert windows vst dll to linux libraries using LinVst.')
parser.add_argument('--linvst',action='store',  default='/usr/share/LinVst/linvst.so', type=str,
                    help='path of linvst.so (default to "/usr/share/Linvst/linvst.so".')
parser.add_argument('dllfile', action='store', type=str, help='dll file toconvert.')

args = parser.parse_args()

dllfile = args.dllfile
linvstlib = args.linvst

if not dllfile.endswith( ".dll" ) and not dllfile.endswith( ".DLL" ) and not dllfile.endswith( ".Dll" ):
    print( "please provid a dll file as an argument (must end with dll, DLL or Dll )." )
    os.exit( 1 )

sofile = dllfile[ 0: -4 ] + ".so"

shutil.copyfile( linvstlib, sofile );

print("done.")
